#!/bin/bash

# Joe Jevnik
# 24.9.2013

# Initializes snipper for first use.

if [ ! -d "$HOME/.snipper" ]; then
    mkdir "$HOME/.snipper"
fi
if [ ! -f "$HOME/.snipper/.snips" ]; then
    touch "$HOME/.snipper/.snips"
fi
